### ISSUE TITLE
Dependency trouble when installing through npm?

### ISSUE THREAD

**Issue by ashleydavies** [Reselim/roact-router#2]
Hi @Reselim, thanks for making all of these Roact projects open source, it's really helpful and generous of you.

I was wondering if you could assist with an issue I've encountered when installing via npm. I'm syncing into a place using Rojo 6.0.2, and have the following packages installed:

```
    "@rbxts/net": "^2.0.0-rc.3",
    "@rbxts/roact": "^1.3.0-ts.10",
    "@rbxts/roact-router": "^1.0.0"
```

However when running a place, I get the following error:

```
  03:08:23.050  ReplicatedStorage.rbxts_include.node_modules.roact-router.src.Roact:5: Roact Router failed to find Roact. Did you make sure Roact is in the same folder?  -  Client - Roact:5
```

I'm a bit lost on how to fix it, and was hoping you'd be able to point me in the right direction. I guess I could put Roact in the right folder in my `node_modules`, but I expect `npm` wouldn't like that and it'd come back to bite me, so I'm fairly sure I've done something wrong or misunderstood how to use this project.

I hate to add any burden to open source devs, and totally understand if you don't have the bandwidth to respond to this; apologies if so.

**Comment by ashleydavies** [comment]
I wonder whether something akin to:

```lua
local container = script.Parent.Parent
local roactModule = container:FindFirstChild("Roact")
local Roact = nil

if not roactModule then
	-- If the rbx-ts runtime is around, try loading with that
	local rbxts = game:GetService("ReplicatedStorage"):FindFirstChild("rbxts_include")
	if rbxts ~= nil then
		local TS = require(game:GetService("ReplicatedStorage"):WaitForChild("rbxts_include"):WaitForChild("RuntimeLib"))
		Roact = TS.import(script, TS.getModule(script, "roact").roact.src)
	else
		error("Roact Router failed to find Roact. Did you make sure Roact is in the same folder?")
	end
else
	Roact = require(roactModule)
end

return Roact
```

Might help solve this? Although this feels pretty hacky

**Comment by Reselim** [comment]
Good catch! I haven't imported other dependencies with roblox-ts before. This project is currently on the backburner, but when I get back to it I'll certainly figure out a solution for this.

**Comment by ashleydavies** [comment]
Awesome, thanks for verifying it isn't on my side!

The hack I did above does work so I'll probably just patch that in locally. Happy to send up a PR if you like? It shouldn't impact users not using `npm`

**Comment by Reselim** [comment]
Yeah, send a PR in!
